[[main]]
none = "none"

[[main]]
name = "about"
pageRef = "about"
identifier = "twmNTO0JZS"
weight = 9_999

[[main]]
name = "contact"
pageRef = "contact"
identifier = "zNDaUphfDf"
weight = 9_999

[[main]]
  name = "posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "albums"
  pageRef = "albums"
  weight = 20

[[footer]]
none = "none"
